### ISSUE TITLE
Change feature size?

### ISSUE THREAD

**Issue by Zhenxing-Dong** [computational-imaging/neural-holography#5]
Hello,

Why did I get a poor result in training HoloNet with ideal ASM propagation when I changed the feature size to 3.74um?

Do I need to change any corresponding parameters?

Thank you!

**Comment by Jungmo** [comment]
Hello, @Zhenxing-Dong , did you find any answer for this?

@choisuyeon, @evanypeng  
Hello, thank you for sharing the good paper and implementation. I'm trying to reproduce it by modifying the pixel pitch (3.6um) and propagation distance (8 cm) by perfect propagation model, but the result is blurry. What part can I modify that will help?
안녕하세요, 좋은 논문과 구현 공유 감사합니다. perfect propagation model 로 픽셀 피치 및 전파거리 수정하여 재현해보고 있는데요, (3.6um) 결과가 흐리게 되는데 혹시 어떤 부분을 수정하는게 도움이 될까요?


This is my answer.
[At Iine 171 of train_holonet.py](https://github.com/computational-imaging/neural-holography/blob/d2e399014aa80844edffd98bca34d2df80a69c84/train_holonet.py#L171C10-L171C10), there is no parameter about pixel pitch for HoloNet class, thus even if I change pixel pitch at line 90, the modified pixel pitch is not considered by HoloNet.
